import { readFileSync, existsSync } from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root = new URL('./', import.meta.url);
const read = name => readFileSync(new URL(name, root), 'utf8');
const app = read('app.js');
new vm.Script(app);
new vm.Script(read('sw.js'));
const elements = new Map();
const document = { getElementById(id) { if (!elements.has(id)) elements.set(id, { style: {}, setAttribute() {}, textContent: '' }); return elements.get(id); } };
let saved = null;
const context = vm.createContext({ document, Intl, Date, JSON, setTimeout: () => 0, clearTimeout() {}, localStorage: { getItem: () => saved, setItem: (_, value) => { saved = value; } } });
const definitions = app.slice(0, app.indexOf('const STORAGE_KEY'));
const funcs = ['loadState','saveState','saveStateIndicator','allItems','updateProgress','buildReport','escapeHtml'];
// Compile actual application functions, omitting browser event wiring and rendering.
let code = definitions + "\nconst STORAGE_KEY='test'; let state={items:{},notes:'',vehicle:''}; let saveTimer; const saveStateEl=document.getElementById('saveState');\n";
for (const name of funcs) {
  const start = app.indexOf('function ' + name + '(');
  const next = app.indexOf('\n}\n', start);
  code += app.slice(start, next + 3) + '\n';
}
vm.runInContext(code, context);
const run = s => vm.runInContext(s, context);
assert.equal(run('CATEGORIES.length'), 8);
assert.equal(run('allItems().length'), 48);
assert.equal(run('new Set(allItems().map(i=>i.id)).size'), 48);
assert.equal(run('CATEGORIES.every(c=>c.items.length===6)'), true);
assert.equal(run('buildReport().pending.length'), 48);
run("state.items.vin={status:'ok',note:'VIN vérifié'};state.items.paint={status:'issue',note:'Rayure aile'};state.items.rearfeatures={status:'na',note:'Sans écran'};state.notes='Réserves transmises';saveState()");
assert.equal(elements.get('doneCount').textContent, 3);
assert.equal(elements.get('naCount').textContent, 1);
assert.equal(run('buildReport().ok'), 1);
assert.equal(run('buildReport().pending.length'), 45);
for (const text of ['VIN vérifié', 'Rayure aile', 'Sans écran', 'Réserves transmises']) assert.ok(run('buildReport().text').includes(text));
assert.equal(run('loadState().items.paint.note'), 'Rayure aile');
saved = '{bad'; assert.equal(run('Object.keys(loadState().items).length'), 0);
saved = '{"items":null,"notes":12}'; assert.equal(run('loadState().notes'), '');
run("localStorage.setItem=()=>{throw Error('full')};saveState()");
assert.match(elements.get('saveState').textContent, /indisponible/);
assert.equal(run("escapeHtml('<script>')"), '&lt;script&gt;');
const html = read('index.html');
for (const [, id] of app.matchAll(/getElementById\('([^']+)'\)/g)) assert.ok(html.includes('id="' + id + '"'), `Missing #${id}`);
const manifest = JSON.parse(read('manifest.webmanifest'));
assert.equal(manifest.start_url, './');
assert.equal(manifest.scope, './');
for (const icon of manifest.icons) assert.ok(existsSync(new URL(icon.src, root)));
// Exercise offline navigation, app-only cache cleanup and pre-cache asset existence.
const handlers = {};
let deleted=[]; let cachedAssets=[]; let claimed=false;
const cache = { addAll: async assets => { cachedAssets=assets; }, match: async path => path === './index.html' ? 'OFFLINE_HTML' : 'CACHED_ASSET' };
const sw = vm.createContext({ URL, self: { registration: {scope:'https://example.com/tesla-model-y-check/'}, addEventListener: (name, cb)=>handlers[name]=cb, skipWaiting: async()=>{}, clients:{claim:async()=>{claimed=true;}} }, caches: {open:async()=>cache, keys:async()=>['another-app','model-y-check-v1','model-y-check-v2'], delete:async key=>deleted.push(key)}, fetch:async()=>{throw Error('offline');} });
vm.runInContext(read('sw.js'),sw);
let promise;
handlers.install({waitUntil:p=>promise=p});await promise;
for (const asset of cachedAssets) assert.ok(existsSync(new URL(asset,root)));
handlers.activate({waitUntil:p=>promise=p});await promise;
assert.deepEqual(deleted,['model-y-check-v1']); assert.ok(claimed);
handlers.fetch({request:{url:'https://example.com/tesla-model-y-check/',method:'GET',mode:'navigate'},respondWith:p=>promise=p});
assert.equal(await promise,'OFFLINE_HTML');
handlers.fetch({request:{url:'https://example.com/tesla-model-y-check/styles.css',method:'GET',mode:'cors'},respondWith:p=>promise=p});assert.equal(await promise,'CACHED_ASSET');
let intercepted=false;handlers.fetch({request:{url:'https://example.com/other-app/',method:'GET',mode:'navigate'},respondWith:()=>intercepted=true});assert.equal(intercepted,false);
console.log('PASS: 48 unique checks / 8 steps; progress; notes; report; storage recovery; asset paths; offline cache; isolated cleanup.');
